version: '3.8'

services:
  nginx:
    image: nginx:alpine
    environment:
      TZ: Europe/Moscow
    hostname: host.docker.internal
    ports:
      - "8088:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./runtime/data/nginx/logs:/var/log/nginx
      - ./:/var/www/html
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
    environment:
      TZ: "Europe/Moscow"
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG:-serverName=docker}
      XDEBUG_TRIGGER: "yes"
    volumes:
      - .:/var/www/html
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./runtime/data/php/logs:/var/log/php
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: [ "CMD", "php-fpm", "-t" ]
      interval: 5s
      timeout: 3s
      retries: 3
  php-cli:
    build:
      context: ./docker/queue
      dockerfile: Dockerfile
    entrypoint: [ "php", "yii", "queue/listen"]
    environment:
      TZ: "Europe/Moscow"
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG:-serverName=docker}
      XDEBUG_TRIGGER: "yes"
    volumes:
      - .:/var/www/html
      - ./runtime/data/php/logs:/var/log/php
    depends_on:
      php-fpm:
        condition: service_healthy
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mysql:
    image: mysql:8.0-oracle
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-}
      MYSQL_DATABASE: ${DB_DATABASE:-base}
      MYSQL_PASSWORD: ${DB_PASSWORD:-}
    ports:
      - "3310:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 1s
      retries: 60

  redis:
    image: redis:7.4.0-alpine
    environment:
      TZ: Europe/Moscow
    ports:
      - "127.0.0.1:6388:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]

volumes:
  mysql_data:
  redis_data:
